language: php
php:
- 5.2
script:
- php -l *.php
branches:
  only:
  - "/\\d\\.\\d\\.\\d/"
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/formaloo-form-builder
  - secure: n3KLioNIiQCrEdmbLTYi/dyOfdEs4nSIffPfBWzQR2bDCuzxYsfcRXycSFBMuSda78nT0S2fABBjslmP5CmvQpXR2aFiu/kqBBdS3mdasQcvPWyYN7nigkWFSoCUsZ39aOqMDsatAxU6wD4yBd/u+h1zc2IPsq/KrOllxQEx65Oxd00LuDeMIceYk9rTVuPVSL6w8Nha1T0rdw3Tv3Ll7rYnHN/JLU6uGazTJ1D8oK7vFrNUU/78RDZXHQhidpHBTqlCgzyxyyn/ABoMSzxliKTA/unlqA88aE7T+fBTIvBenOrORxwPSfWnjx44oPcv5b5FRBFzOEXKg0XgHENU3EneGqYqsavBVwu2gZZASNOE4CNKs2aOC1GSthtAA83W3PUoCQEXwbPFOreeHUz/zTASdObJLCly4lOVd22FuD5uKTjjQpVA3dmLJ4sCnSPApv5ieeOkJJRM7FIBQVRjclF2XJTvk+P1MMrMHyh1yjlSBJb0QloGVjMsWEPWOiITxCo6aZ5xGt8JutnL5HydINJdJIlS0OjU89i7zvxR9e8QwMDyVSmA+bxHLlvBGn5dosl7bkenECksYsEzMThj2r7joBQOyWy6f1j3sIqJbA9jK2JgMUEjcow2T8Q/wnU2UNideyv7mhvzkBm5uTNeUID5yIAADtES78cW7VH/Wb8=
  - secure: LY9cSoYj071O+TVxxfNQ4uO12KGt/jeM0iNcmKD+Dc+aoDN4lB99T3MHxZTBNp+r3i9Amu+Y0Qpifd4CeOBhUtsesqGnY+fLdytL2m/ShtTACDtiT0EiQw+TVRhs5tvv3JJXMBv/QHvomQbT4Wb2cbCfPVKvfEkKHzI3XEoeaBURGNAgYhnOWnThvc1UKhlgMepMKlBi9Tz1r7/A+4dCKYLO3tu1PzgFy0qptpZYjcyPBdXQz/tJjAIA8E6r2OB9jeq1qtut9MJ5vq9lI84ZXpGqIDSdSg1sgbOXIsd5WIeH0jtBY8z5d8nYCLqDYjKS/45OLXsVq36kka57g0w+FD6KLwT+ViwBlgPvrH7tgW+jKjjeTK4VTqAesbLmze/t1Av/7Uiirnj8sallAD5lwWoguiAi9LU1mJc1cDzJOsFlWvL9V2tE8l8O9dy00Ao5j0rl5DsdXmFIyh8lTKqhbzv62AXmlqcAdmM+Ng5XLWuiZapjTKb+R35T/DCzd3is5T0h8s/dkLmqIGQN1kL0RhuXWKvEjKAJHk/Nv1fY4CyFht+qYtkeBZYK9p9sBEqe5CGkPvC4mxT1qUpBVKw55tE1bTceBnJtFbzkssPIgpDMTvV8PW+TuvpXXkKe7MiVXhok0q8N4XQHPjSpexZMD76Rmf2xTzpKMkJVhUK+S4g=
